### ISSUE TITLE
Git Integration?

### ISSUE THREAD

**Issue by Shadow53** [Shadow53/hoard#1]
I'm thinking something like using gitoxide to turn the saves folder into a git repository. Then we can do something like chezmoi init and download the git repo on new machines, make snapshots of the saves at different points in time, etc.

**Comment by mmstick** [comment]
I think if someone wants to use git, they'll set this up themselves. A person might prefer using other systems too, like pijul.

**Comment by Shadow53** [comment]
I'm inclined to agree. I think a better alternative to something like this -- though not 1-to-1 -- is to provide some subcommands that are useful for scripting the behavior of `hoard`.
