### ISSUE TITLE
Detect file diffs

### ISSUE THREAD

**Issue by Shadow53** [Shadow53/hoard#12]
The purpose of `hoard` is to make it easy to synchronize random scattered files across machines, so it would be useful to have a way to detect the presence of unsynced changes.

# Current Thoughts

- One or more files in `hoards_root` that define the last time a hoard was backed up/a log of X recent backups
- A similar file in a cache location, e.g. `$HOME/.cache/hoard` on \*nix systems
- If there is a difference in the two files, inform the user
  - Four obvious cases:
    1. Local is more recent: warn on `restore`
    2. Remote/backup is more recent: warn on `backup`
    3. Both local and remote have divergent changes: inform user and let them handle conflicts
    4. Files are in sync: no changes or warnings

In the cases of warnings, the operation would abort until it is resolved. Users can force resolution by using a `--force` flag.

If files are being restored for the first time, the record file would get copied to the cache location.

If done right, this should have an added benefit of allowing users to incorporate `hoard` in shell rc files and scripts, where they will do nothing if there might be problems.

**Comment by mmstick** [comment]
You won't need to check for differences if just using the modified time. Any differences in the mtime of a file will instantly show that a file has changed.

**Comment by Shadow53** [comment]
The thing is, I don't want something like `touch myfile` to count as a "difference." Differing files should be based on existence and content, IMO.

So if a file exists in the hoard, does not exist on the filesystem, and would be copied to the filesystem with `hoard restore`, that's a "diff." Same for the opposite case, and for cases where the backed up version has different content from the one on the filesystem.

**Comment by mmstick** [comment]
That'd be rather intense on I/O and CPU with a lot of files

**Comment by mmstick** [comment]
It may seem silly, but simply syncing a file that was touched sounds better than spending a lot of resources diffing files.

**Comment by Shadow53** [comment]
You have a point. There's also some merit to the thought of at least using mtime to short-circuit a diffing process. I am not going to make a decision on this quite yet, as there are at least a couple other features that would also be affected.

**Comment by Shadow53** [comment]
Some notes on comparing things in case I go down that route.

- If I am checking whether a hoard has *any* differences, I can stop checking after the first difference found.
  - Search first for files existing in one location and not the other.
  - Then check file contents.
- When comparing files, byte-by-byte is more efficient than checksums (ignoring caching).
- It is generally faster to read a bunch of one file than it is to switch back and forth, so use a buffered reader.
  - This also includes using multiple threads, since it is still just one disk controller.
  - I expect `hoard` to more likely be used with a bunch of small files rather than a bunch of large ones, so reading entire files into memory before comparing is also an option, for some maximum size.
- File contents only need to be checked if file lengths are the same.

**Comment by Shadow53** [comment]
Closing in favor of #26
