### ISSUE TITLE
Incorrect config file location in Windows

### ISSUE THREAD

**Issue by johnw42** [Shadow53/hoard#135]
According to the documentation, the config file in Windows should be at `%APPDATA%\shadow53\hoard\config.toml`, but the actual location is `%APPDATA%\shadow53\hoard\config\config.toml`.

**Comment by Shadow53** [comment]
Thanks for the report! This looks to be an issue with the documentation, as I believe that actual path is correct.

**Comment by Shadow53** [comment]
Resolved in #144
