### ISSUE TITLE
Add init subcommand

### ISSUE THREAD

**Issue by doychi** [Shadow53/hoard#161]
It would be awesome if an init subcommand could be added.

The command should (based on the options selected):
* Create the directories used by Hoard, including the:
  * configuration directory
  * data directory
* Create an empty (or example) configuration file

This will allow new users to run the init subcommand to have the locations created and know where they need to set put their version control repos or point their synchronisation solutions.

**Comment by Shadow53** [comment]
Good idea! I'll try to get to this this weekend.

**Comment by Shadow53** [comment]
Sorry for taking so long on this -- I implemented most of the code and lost track of finishing it up. Code is merged now, and I will create a new release after updating dependencies.
