### ISSUE TITLE
Handling deleted files

### ISSUE THREAD

**Issue by Shadow53** [Shadow53/hoard#21]
Right now, no concern is given to when files are deleted.

- If an entire pile is deleted from the filesystem and user runs `hoard backup`, the copying process will fail with a warning
  - Same with a pile being deleted from the hoards folder and user runs `hoard restore`.
- If a single file from a directory pile is deleted from the filesystem, it is not copied on backup (because it does not exist) but will be restored with `hoard restore`.
  - Similar for the opposite situation.

This brings up some questions:

# (How) do we detect a deleted file?

This question is related to #12 and should primarily be discussed there. As far as this issue is concerned, there is the possibility of knowing that a file was deleted *from* a pile (e.g. by a different machine), a separate possibility of knowing a file was deleted from the filesystem, and not knowing the previous state at all.

# What do we do if we discover a file has been deleted/is missing?

Depends on implementation details.

## We have some record that the file existed and now doesn't

  - Do we know the user intentionally deleted the file? The answer is probably no. The safest option is to warn the user and abort, and provide option flags that prevent the abort in favor of one of the following:
    - Ignore missing files: Basically perform the operation, but skip any files marked as missing. This means no deleting the version that still exists (e.g., the backup when backing up) and no replacing the file that was deleted.
    - Keep deleted files: Do not delete any files, but replace missing ones as applicable.
    - Force deletion: Do not replace any files, but delete "orphans".
  - This means extra cognitive effort on the part of the user to remember to use the appropriate flag or always run the command twice.
  - Alternatively, there is the possibility of adding an interactive piece to the program where the user can tell `hoard` whether a file was intentionally deleted.

## We don't have such a record

This is similar to the above, but we no longer know the difference between a newly created file and a newly deleted one.

- Warn/etc. whenever the wrong file exists, i.e. only the backup exists while backing up or the original exists while restoring. Provide a `--force` flag to make the operation happen anyways.
- Don't care and propagate possible deletions, i.e. delete the backup if backing up while the original file is missing. Assume the user has good backups/is using git.

# Missing files and checking if a clean backup/restore can happen

Also related to #12 and the possibility of having commands to check if a clean backup or restore can happen (i.e. no changes will be clobbered). I think the following applies:

- We keep records of file existence:
  - If the file did not previously exist, copying existing file to other location is considered "clean"
  - If it did previously exist, this is a potential conflict and needs to be manually resolved.
- We do not keep records:
  - Retaining the existing file is considered "clean", deleting the file is not.
  - Not caring is always considered "clean". At that point, though, a check for a clean application does not make sense.

**Comment by Shadow53** [comment]
This is probably the weakest part of `hoard`'s design. Other dotfile managers make this work with `<cmd> rm <file>` but since `hoard` doesn't operate on files but on collections of them, there is not a direct way to keep track of files within a directory pile.

**Comment by mmstick** [comment]
You would just have a restore bit for each file. If you have restored a file, and then later that file is missing, then it has been removed.

**Comment by Shadow53** [comment]
> You would just have a restore bit for each file. If you have restored a file, and then later that file is missing, then it has been removed.

There are some edge cases that would need to be covered, but this would be the general idea. It was a little after midnight here when I wrote the original post, so I'd like to clarify some thoughts for anyone reading this thread.

In essence, I was conflating a few different questions: (1) how do we tell if a file has disappeared from the filesystem, (2) how do we tell if that file was *intentionally* deleted by the user, and (3) do we care about that difference, with some discussion about what happens if we *do* care.

I have some ideas for (1), which is a bit more robust than @mmstick's comment but along the same idea. More on that in another comment.

----------------

I think for (3) that arguments can be made for both sides. There are definitely circumstances in which a blind deletion of files is likely to cause problems. Consider someone backing up save data for a PC game on Linux, where that save data is relative to the game's installation directory. They have configuration for two different installations of Steam, a native install and one through Flatpak. They have a brain fart moment and run `hoard backup game`, thinking it will back up files for the native install (where they actually have save data) but instead "backs up" the empty saves directory for the Flatpak install (which is set to take precedence).

If there is no special logic for deleted files, this person's existing backup would be wiped away on accident. They ideally have some sort of backup, but not all situations are ideal and I'd like to try to prevent at least *some* instances of things like this.

----------------

Which brings us back around to (2), how to tell whether the user wanted those files deleted.

In the above example, the best thing to do would be to recognize the change in environment by comparing the path to back up with the path used in the last backup/restore. If they are different, warn the user and require some flag to be used, like `--allow-change-path`.

It's a little more difficult to tell what to do when that path doesn't change, though.

- What's the likelihood that someone *accidentally* deletes a single, usually hidden file?
  - Not nearly as likely as someone intentionally deleting the file.
  - Are backups/version control enough to cover this situation? Just about every synchronization program I can think of provides some sort of versioning.
  - Which adds up to more annoyance over time: users accidentally deleting files, or users constantly needing to provide some CLI flag that says "I want to propagate this deletion" AND the extra complexity of implementing such code?
- What about if a file is deleted on one machine, the hoard deletion is synchronized, but then the user does a backup on another machine where `hoard restore` did not apply that deletion?
  - If changes get tracked across machines, `hoard` should be able to catch this situation and handle it.
  - OTOH, tracking changes across multiple machines is not a simple thing to do robustly.

I am going to revisit this later, but I am currently thinking of preventing the specific cases of changed paths and undoing synchronized creation/deletion, but leaving the general "oops I deleted a file and then did a backup that deleted that one too" as something for users to deal with using backups and/or versioning of some sort.

**Comment by Shadow53** [comment]
Recording more thoughts here about designing this.

-------------------

I think specifically preventing "different path matched" and "file creation/deletion was synced then undone" are still the best middle ground for this. Both features will require recording some amount of transaction history.

- Different path matched
  - Local only
  - A record of the last path matched in either a backup or a restore. Essentially a dump of the corresponding `Hoard`/`Pile` object.
- File create/delete synced
  - Need to know all creations and deletions on other devices since some time in the past.
  - Need to record said creations/deletions
  - Need to keep track of last operation on this machine to know how far back to check
  - Need to have unique machine ids to separate records per machine

I am thinking some sort of structure like this in the program's data directory (e.g. `${XDG_DATA_HOME}/hoard/` on Linux).

```
(data dir)
├ hoards
│    ├ hoard_1
│    └ ...
└ history
     ├ machine-uuid-1
     │    ├ last_paths.json
     │    ├ last_create_delete_timestamps.json
     │    └ file_creation_deletion
     │            ├ some-utc-timestamp.json
     │            └ ...
     └ ...
```

- `last_paths.json`: a JSON file containing mappings of the last path matched for every file in every pile in every hoard. Structure would look something like:
  ```json
  {
    "hoard_name": {
      "pile_name": {
        "path/relative/to/pile": "/absolute/path/on/system"
      }
    }
  }
  ```
  Where `"pile_name"` is an optional level, if there are named piles. Otherwise the paths would go directly under `"hoard_name"` for anonymous piles.
- `last_create_delete_timestamps.json`: A mapping of hoard/piles to a map of machine ids to utc timestamps:
  ```json
  {
    "hoard_name": {
      "pile_name": {
        "machine-uuid": "YYYY-MM-DDZhh:mm:ss.sss",
      }
    }
  }
  ```
- `file_creation_deletion/{timestamp}.json`: files named by timestamp of the operation they are logging. Only keeps track of files that are created (did not previously exist in the hoard) or deleted (no longer exist in the hoard).
  ```json
  {
    "hoard_name": {
      "pile_name": {
        "path/relative/to/pile": "created",
        "path/also/relative": "deleted"
      }
    }
  }
  ```

------------

There will also be a file in the project config directory (e.g. `${XDG_CONFIG_HOME}/hoard/machine-id`) containing a single UUIDv4 to differentiate multiple machines.

------------

The various log files will be JSON to help indicate that they are data files generated by and for `hoard` and not intended for human editing, unlike TOML files.

**Comment by Shadow53** [comment]
Closing in favor of #26
