### ISSUE TITLE
Feature request: Ignore subfolders

### ISSUE THREAD

**Issue by lmburns** [Shadow53/hoard#27]
If there is a large directory that I would like to backup that contains some folders within it that I'd like to ignore, it would be nice to be able to provide some sort of regex to ignore that pattern. The specific case I am referring to is that I am backing up my `vimwiki` directory and it contains a `.git` folder. On the first go-around it works perfectly fine; however, whenever I try to back it up a second time once something has changed, I get this error:

```
ERRORfailed to back up vimwiki: failed to copy /Users/lucasburns/vimwiki/music/.git/objects/0e/b565c87706e00
ec8efd3834f074db5175210e7 to /Users/lucasburns/.config/hoard/root/vimwiki/dir/music/.git/objects/0e/b565c87706
e00ec8efd3834f074db5175210e7: Permission denied (os error 13)
    at src/main.rs:16
```

If there is something I can do already to fix this, I can try and see if that would work.

**Comment by Shadow53** [comment]
The permission denied error seems odd, though that may be related to how git works internally.

Focusing on the feature request, ignored folders is a good feature to include.

**Comment by Shadow53** [comment]
@lmburns I've implemented a basic ability to ignore paths based on glob patterns in branch `27-ignore-subfolders`. Please try the new changes and see if it works for you. See `ci-tests/config.toml` for an example of how to configure an ignore pattern.

You can install the version based on this branch with
```
cargo install hoard --git https://github.com/Shadow53/hoard.git --branch 27-ignore-subfolders
```
