### ISSUE TITLE
Version 0.4.0 for x86_64-unknown-linux-gnu prints errant error message

### ISSUE THREAD

**Issue by noahrubin** [Shadow53/hoard#73]
Version: `0.4.0`
Platform: `x86_64-unknown-linux-gnu`

# Observed Behavior

```bash
> hoard --help
ignoring ``: invalid filter directive
hoard 0.4.0
The possible subcommands for `hoard`

USAGE:
    hoard [FLAGS] [OPTIONS] [SUBCOMMAND]

FLAGS:
    -f, --force      
        --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -c, --config-file <config-file>    
    -h, --hoards-root <hoards-root>    

SUBCOMMANDS:
    backup      Back up the given hoard(s)
    cleanup     Cleans up the operation logs for all known systems
    help        Prints this message or the help of the given subcommand(s)
    list        List configured hoards
    restore     Restore the files from the given hoard to the filesystem
    validate    Loads all configuration for validation. If the configuration loads and builds, this command succeeds
```
Notice the `ignoring ``: invalid filter directive` message at the top (printed to stderr). This happens on every invocation of `hoard`.

# Expected Behavior

Running `hoard --help` should only produce the help message. 

# Steps to Reproduce

1. [Download archive](https://github.com/Shadow53/hoard/releases/download/v0.4.0/hoard-x86_64-unknown-linux-gnu.tar.gz) from GitHub and unzip it.
2. Run `hoard --help`

**Comment by Shadow53** [comment]
I am able to reproduce this locally. I will need to investigate what is causing it, though.

**Comment by noahrubin** [comment]
Another interesting aspect of this potential bug is that I cannot reproduce it when running with `HOARD_LOG={trace,debug,info,warn,error} hoard --help`. It only appears when running without that env variable set.

**Comment by Shadow53** [comment]
This should be resolved in `main` now and will be in the next release
