### ISSUE TITLE
Specify path for .bashrc file in $HOME directory

### ISSUE THREAD

**Issue by noahrubin** [Shadow53/hoard#74]
Version: `0.4.0`
Platform: `x86_64-unknown-linux-gnu`

I have a hoard named `bash` that contains two piles:

```toml
# Bash rcfile
[hoards.bash.rcfile]
"linux" = "${HOME}/.bashrc"

# Bash aliases directory
[hoards.bash.aliases]
"linux" = "${HOME}/.bash_aliases.d/"
```
The file structure at the hoards root looks like this:

```bash
bash/:
drwxrwxr-x  3 dev dev 4.0K Dec 31 14:33 aliases/
drwxrwxr-x  2 dev dev 4.0K Dec 31 14:33 rcfile/

bash/aliases:
drwxrwxr-x 2 dev dev 4.0K Dec 31 01:05 .bash_aliases.d/

bash/aliases/.bash_aliases.d:
-rw-rw-r-- 1 dev dev  349 Dec 31 01:04 00-primary-aliases.sh

bash/rcfile:
-rw-r--r-- 1 dev dev 1.9K Dec 31 01:34 .bashrc
```

However, when I run `hoard restore bash` I end up with the following directory structure under `$HOME`:

```bash
❯ hoard restore bash
ignoring ``: invalid filter directive
WARN hoard::checkers::history::operation: path is neither file nor directory, skipping: path=/home/<user>/.bash_aliases.d
WARN hoard::checkers::history::operation: path is neither file nor directory, skipping: path=/home/<user>/.bashrc
restoring hoard: hoard=bash

 ❯ la ~/ | grep bash
drwxrwxr-x  3 dev  dev  4.0K Jan  1 00:11 .bash_aliases.d/
drwxrwxr-x  2 dev  dev  4.0K Jan  1 00:11 .bashrc/

 ❯ la ~/.bashrc
-rw-rw-r--  1 dev dev 1.9K Jan  1 00:11 .bashrc

 ❯ la -R ~/.bash_aliases.d/
/home/dev/.bash_aliases.d/:
drwxrwxr-x  2 dev dev 4.0K Jan  1 00:11 .bash_aliases.d/

/home/dev/.bash_aliases.d/.bash_aliases.d:
-rw-rw-r-- 1 dev dev  349 Jan  1 00:11 00-primary-aliases.sh
```
In other words, `hoard` creates an extra level of directories instead of placing my bashrc in `${HOME}/.bashrc` and my aliases in `${HOME}/.bash_aliases.d/`. Am I configuring `hoard` incorrectly or is this a bug?

**Comment by Shadow53** [comment]
Thank you for the detailed bug report!

This appears to be a bug, but one that should have been caught by CI. The hoards root *should* look like this:

- bash/
  - rcfile
  - aliases/
    - [contents of .bash_aliases.d]

So it looks like `hoard restore` is restoring files correctly, but `hoard backup` might not be backing them up correctly. I will try to recreate this and see if there is any errant logic happening.

**Comment by Shadow53** [comment]
I was not able to recreate this. I started up a scratch Alpine container, downloaded the latest Hoard release with `wget`, and created the following config:

```
[envs]
linux = { os = ["linux"] }

[hoards]
[hoards.bash.rcfile]
"linux" = "${HOME}/.bashrc"

[hoards.bash.aliases]
"linux" = "${HOME}/.bash_aliases.d/"
```

This is the result:

```
/ # tree ~/.local/share/hoard/hoards/
/root/.local/share/hoard/hoards/
└── bash
    ├── aliases
    │   └── 00-primary-aliases.sh
    └── rcfile

2 directories, 2 files

/ # cat ~/.local/share/hoard/hoards/bash/rcfile 
RCFILE

/ # cat ~/.local/share/hoard/hoards/bash/aliases/00-primary-aliases.sh 
PRIMARY ALIASES
```

If it won't cause any loss of data for you, please try recreating this again on your machine. I suggest deleting the entire `~/.local/share/hoard` directory beforehand.

If it still happens, please provide the following:

- The entire `config.toml` file
- The output of `hoard backup bash` with `env HOARD_LOG=trace hoard backup bash 2>&1 1>backup-output.log`
- The output of `hoard restore bash` using the same command as above, but with `hoard restore`.

**Comment by noahrubin** [comment]
It was definitely my misunderstanding. When reading the [File Locations](https://hoard.rs/file-locations.html) section of the documentation I mistakenly thought that Pile sources within a Hoard could only be directories, not files _or_ directories. I was trying to think of a way to make the documentation clearer, but after reading it again I think it's sufficient the way it is. Thanks for the response.
